{% set name = "ridgeplot" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ridgeplot-{{ version }}.tar.gz
  sha256: 40367de914cc9c902e865995f947cbb8dc514cb4d92158e47536f2a40e733047

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1
    - plotly >=5.20
    - statsmodels >=0.12,!=0.14.2
    - typing_extensions
    - importlib-resources

test:
  imports:
    - ridgeplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tpvasconcelos/ridgeplot
  summary: Provides a simple interface for plotting beautiful and interactive ridgeline plots within the extensive Plotly ecosystem.
  doc_url: https://ridgeplot.readthedocs.io/en/stable/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
