schema_version: 1

context:
  name: ridgeplot
  version: 0.4.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ridgeplot-${{ version }}.tar.gz
  sha256: 05361a6fee10c819a803b4837da64a87b776d8a9d3684001c597738b80e1c45c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1
    - plotly >=5.20
    - statsmodels >=0.12,!=0.14.2
    - typing_extensions
    - importlib-resources

tests:
  - python:
      imports:
        - ridgeplot
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Provides a simple interface for plotting beautiful and interactive ridgeline plots within the extensive Plotly ecosystem.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tpvasconcelos/ridgeplot
  documentation: https://ridgeplot.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - thewchan
